name: Build recovery Image

on: 
  push:
    branches:
      - master
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-18.04

    env:
      VENDOR: motorola
      DEVICE: guamp
      ANDROID_ROOT: /home/runner/work/fox_10.0

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y python python-dev make git
        sudo docker rmi `docker images -q`
        mkdir -p /home/runner/work/twrp/
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php \
          .cache \
          /var/cache/* \
          /usr/local/share/boost \
          /opt/ghc \
          $AGENT_TOOLSDIRECTORY 
    - name: Downloading source code
      run: |
        source of.env
        mkdir -p $ANDROID_ROOT
        git config --global user.name "OrangeFox Volla Phone CI"
        git config --global user.email "thisemaildoesnotexist@exist.com"
        sudo apt install git aria2 -y
        git clone https://gitlab.com/OrangeFox/misc/scripts
        cd scripts
        sudo bash -c "yes || true" | setup/android_build_env.sh
        sudo bash -c "yes || true" | setup/install_android_sdk.sh
        cd 
        git clone https://gitlab.com/OrangeFox/sync.git sync
        cd sync
        ./get_fox_10.sh $ANDROID_ROOT
        cd $ANDROID_ROOT
        mkdir -p device/motorola/guamp
        git clone https://github.com/snjy4/twrp11 device/motorola/guamp
    - name: Build recovery
      run: |
        chmod +x build.sh
        bash -x build.sh
      shell: bash

    - name : Upload recovery image
      uses: actions/upload-artifact@master
      with:
        name: Images
        path: /home/runner/out/target/product/fox_10.0/*.img
