name: Build recovery Image

on: 
  push:
    branches:
      - master
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-18.04

    env:
      VENDOR: motorola
      DEVICE: guamp
      ANDROID_ROOT: /home/runner/work/twrp/

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential flex g++-multilib git gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev libwxgtk3.0-dev
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php \
          .cache \
          /var/cache/* \
          /usr/local/share/boost \
          /opt/ghc \
          /boot \
          $AGENT_TOOLSDIRECTOR
        sudo docker rmi `docker images -q`
        mkdir -p ~/bin
        wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
        chmod +x ~/bin/repo
        git config --global user.name "OrangeFox Volla Phone CI"
        git config --global user.email "thisemaildoesnotexist@exist.com"

    - name: Downloading source code
      run: |
        source of.env
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
        repo sync -j2
        git clone https://github.com/snjy4/twrp-10.git device/motorola/guamp
        mkdir -p out/target/product/guamp/
        cp device/motorola/guamp/prebuilt/* out/target/product/guamp/
    
    - name: Build recovery
      run: |
        chmod +x build.sh
        bash -x build.sh
      shell: bash

    - name : Upload recovery image
      uses: actions/upload-artifact@master
      with:
        name: Images
        path: /home/runner/work/twrp/out/target/product/*/recovery.img
