name: Build recovery Image

on: 
  push:
    branches:
      - master
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-18.04

    env:
      VENDOR: motorola
      DEVICE: guamp
      ANDROID_ROOT: /home/runner/work/twrp/
      TZ: Asia/Kolkata

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential flex g++-multilib git gcc-multilib gnupg gperf imagemagick \
        lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev \ 
        libssl-dev libxml2 libxml2-utils lzop pngcrush \
        rsync schedtool squashfs-tools xsltproc zip zlib1g-dev libwxgtk3.0-dev
      
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php \
          .cache \
          /var/cache/* \
          /usr/local/share/boost \
          /opt/ghc \
          $AGENT_TOOLSDIRECTORY
        sudo docker rmi `docker images -q`
        bash -x cleanup.sh
        
        mkdir -p ~/bin
        wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
        chmod +x ~/bin/repo
        git config --global user.name "OrangeFox Volla Phone CI"
        git config --global user.email "thisemaildoesnotexist@exist.com"

    - name: Downloading source code
      run: |
        source of.env
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        
        repo init -c --no-repo-verify --no-clone-bundle --depth=1 --partial-clone --clone-filter=blob:limit=10M -u \
        git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11 -g default,-notdefault,-device,-darwin,-x86,-mips 
        repo sync -j$(nproc --all) -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune
        
        git clone --depth=1 https://github.com/RazaDroidProject/recovery_device_motorola_guamp.git device/motorola/guamp
        export DEVICE_PATH=$ANDROID_ROOT/platform_manifest_twrp_aosp/device/motorola/guamp
 
    - name: Build recovery
      run: |
        sudo rm -rf /var/cache/*
        bash -x build.sh

    - name: Upload recovery image
      run: |
        curl -T /home/runner/work/twrp/out/target/product/guamp/recovery.img https://oshi.at
